[workspace]
members = [
    "tools/*",
    "bioma_actor",
    # "bioma_behavior", 
    "bioma_derive",
    "bioma_llm",
]
resolver = "2"

default-members = ["bioma_behavior"]

[profile.release]
debug = true

[profile.dev.package.askama_derive]
opt-level = 3
