services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - bioma-network

  surrealdb:
    image: surrealdb/surrealdb:v2.0.1
    container_name: surrealdb
    command: start --no-banner --allow-all --bind 0.0.0.0:9123 --user root --pass root surrealkv://data/bioma.db
    user: "1000:1000"
    volumes:
      - surreal_data:/data
    ports:
      - "9123:9123"
    networks:
      - bioma-network

  init-volume:
    image: busybox
    volumes:
      - surreal_data:/data
    command: chown -R 1000:1000 /data

  reranker:
    image: ghcr.io/huggingface/text-embeddings-inference:1.5
    container_name: reranker
    command: --model-id BAAI/bge-reranker-base --max-client-batch-size 256
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    volumes:
      - reranker_data:/data
    ports:
      - "9124:80"
    networks:
      - bioma-network

volumes:
  ollama_data:
  surreal_data:
  veoveo_data:
  reranker_data:
  text_embeddings_data:

networks:
  bioma-network:
    driver: bridge