[package]
name = "bioma_llm"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
uuid = { workspace = true }
thiserror = { workspace = true }
derive_more = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
indexmap = { version = "2.4", features = ["serde"] }
futures = { workspace = true }
humantime = { workspace = true }
humantime-serde = { workspace = true }
jsonpath-rust = { workspace = true }
tracing = { workspace = true }
reqwest = { workspace = true }
url = { workspace = true }
ollama-rs = { version = "0.2.1", features = [
    "chat-history",
    "function-calling",
] }

bioma_derive = { path = "../bioma_derive" }
bioma_actor = { path = "../bioma_actor" }

[dev-dependencies]
test-log = { version = "0.2", default-features = false, features = [
    "trace",
    "color",
] }
color-backtrace = "0.6"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
rand = "0.8"
